version: 0.2

env:
  variables:
    CI_SERVER: "yes"
    CI_COMMIT_REF_NAME: "${CODEBUILD_SOURCE_VERSION}"
    CI_COMMIT_HASH: "${CODEBUILD_RESOLVED_SOURCE_VERSION}"

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - make foo
